// Tests for the camera-metadata projection seam (src/BRAWLensMap.h): the
// minimal calibration-JSON parser and the Mei-Rives map generator that turn
// an URSA Cine Immersive clip's embedded Apple Immersive calibration into
// per-eye equirect STMaps.
//
// The fixture (tests/fixtures/ursa_immersive_calibration.json) is the real
// OpticalProjectionData blob from an URSA Cine Immersive clip. Golden values
// were produced by an independent double-precision Python implementation of
// the same spec — the one whose output was verified visually and numerically
// against decoded frames of that clip
// (docs/2026-08-30-braw-immersive-metadata-projection.md, gen_goldens.py in
// docs/captures/). Build & run: make test
#include "BRAWLensMap.h"

#include <clocale>
#include <cmath>
#include <cstdio>
#include <string>
#include <vector>

static int failures = 0;

static void check(bool ok, const char* name)
{
    if (!ok) {
        ++failures;
        std::fprintf(stderr, "FAIL %s\n", name);
    } else {
        std::printf("ok   %s\n", name);
    }
}

static void expectNear(double actual, double expected, double tolerance, const char* name)
{
    if (std::isnan(actual) || std::fabs(actual - expected) > tolerance) {
        ++failures;
        std::fprintf(stderr, "FAIL %s\n  expected: %.9f (±%g)\n  actual:   %.9f\n",
                     name, expected, tolerance, actual);
    } else {
        std::printf("ok   %s\n", name);
    }
}

static bool loadFile(const char* path, std::string* out)
{
    std::FILE* f = std::fopen(path, "rb");
    if (!f) return false;
    std::fseek(f, 0, SEEK_END);
    const long size = std::ftell(f);
    std::fseek(f, 0, SEEK_SET);
    if (size <= 0) {
        std::fclose(f);
        return false;
    }
    out->resize(static_cast<size_t>(size));
    const bool ok = std::fread(&(*out)[0], 1, out->size(), f) == out->size();
    std::fclose(f);
    return ok;
}

static const float* texel(const ndi_stmap::STMapImage& map, int r, int c)
{
    return map.uv.data() + (static_cast<size_t>(r) * map.width + c) * 2;
}

int main()
{
    std::string json;
    if (!loadFile("tests/fixtures/ursa_immersive_calibration.json", &json)) {
        std::fprintf(stderr, "FAIL cannot read tests/fixtures/ursa_immersive_calibration.json "
                             "(run from the repo root: make test)\n");
        return 1;
    }

    // ---- parse the real calibration -------------------------------------
    ndi_brawmap::LensCalibration cal;
    std::string error;
    check(ndi_brawmap::parseCalibrationJSON(json, &cal, &error), "fixture parses");
    if (failures) {
        std::fprintf(stderr, "  parse error: %s\n", error.c_str());
        return failures;
    }
    check(cal.generator == "Apple Immersive Camera Calibration Service", "generator string");
    expectNear(cal.left.fx, 7765.9024452131525, 1e-6, "left fx");
    expectNear(cal.left.cx, 4080.2881365398475, 1e-6, "left centerX");
    expectNear(cal.left.xi, 2.0429670816469443, 1e-9, "left xi (3rd distortion)");
    expectNear(cal.left.skew, -0.6674811051990651, 1e-9, "left skew");
    expectNear(cal.left.calibLimitDeg, 109.58572387695312, 1e-6, "left calibration limit");
    check(cal.left.imageWidth == 8160 && cal.left.imageHeight == 7200, "left imageSize");
    expectNear(cal.right.fx, 7750.7705728515775, 1e-6, "right fx");
    expectNear(cal.left.quat[3], 0.9999883522213009, 1e-9, "left quat w");
    expectNear(cal.left.maskRadiusDeg, 80.0, 1e-3, "mask circle radius");
    check(cal.left.maskSpreadDeg < 0.01, "mask ring is circular (spread ~0)");
    expectNear(cal.left.maskEdgeDeg, 2.5, 1e-9, "mask edge width");

    // ---- pure projection golden: a ray at half the stated horizontal FOV
    // must land on the sensor edge (the check that pinned the model).
    {
        const double theta = 101.832221984863281 * (M_PI / 180.0);
        ndi_brawmap::MeiProjector projector(cal.left);
        double uPx = 0, vPx = 0;
        check(projector.project(std::sin(theta), 0.0, std::cos(theta), &uPx, &vPx),
              "half-hFov ray projects");
        expectNear(uPx, 8165.5523, 0.05, "half-hFov ray lands at the sensor edge");
    }

    // ---- full-chain goldens (rotation + projection + STMap normalize) ----
    ndi_stmap::STMapImage left, right;
    check(ndi_brawmap::generateLensMaps(cal, 64, false, &left, &right, &error),
          "maps generate at 64 (mask off)");
    check(left.width == 64 && left.height == 64 && right.width == 64, "map dimensions");

    struct Golden { int eye, r, c; float u, v; };
    // Generated by gen_goldens.py (double precision, independent implementation).
    static const Golden kGoldens[] = {
        { 0, 31, 31, 0.494407467f, 0.511253282f },
        { 0, 10, 50, 0.656942072f, 0.897541104f },
        { 0, 55, 20, 0.416245558f, 0.094373405f },
        { 0, 0, 0, 0.488654844f, 1.022041885f },
        { 0, 63, 63, 0.511852107f, -0.018185644f },
        { 0, 31, 0, 0.048621331f, 0.512313952f },
        { 1, 31, 31, 0.494099483f, 0.511502734f },
        { 1, 10, 50, 0.656701294f, 0.898400781f },
        { 1, 55, 20, 0.416043986f, 0.095248368f },
        { 1, 0, 0, 0.488209068f, 1.023565979f },
        { 1, 63, 63, 0.511539843f, -0.016820089f },
        { 1, 31, 0, 0.047686306f, 0.512759864f },
    };
    for (const Golden& g : kGoldens) {
        const ndi_stmap::STMapImage& map = g.eye ? right : left;
        const float* t = texel(map, g.r, g.c);
        char name[128];
        std::snprintf(name, sizeof(name), "golden %s (%d,%d) u", g.eye ? "right" : "left", g.r, g.c);
        expectNear(t[0], g.u, 1e-5, name);
        std::snprintf(name, sizeof(name), "golden %s (%d,%d) v", g.eye ? "right" : "left", g.r, g.c);
        expectNear(t[1], g.v, 1e-5, name);
    }

    // The two eyes' calibrations genuinely differ (distinct intrinsics and
    // rectification) — a swapped or shared-eye bug would collapse them.
    check(std::fabs(texel(left, 31, 31)[0] - texel(right, 31, 31)[0]) > 1e-4,
          "left and right maps differ");

    // The extreme corner projects geometrically fine but lands above the
    // fisheye frame (v > 1): the value is passed through for the warp's
    // own out-of-range handling, not flagged invalid here.
    check(texel(left, 0, 0)[0] >= 0.0f && texel(left, 0, 0)[1] > 1.0f,
          "corner texel is valid-but-out-of-frame");

    // ---- mask ------------------------------------------------------------
    ndi_stmap::STMapImage leftMasked, rightMasked;
    check(ndi_brawmap::generateLensMaps(cal, 64, true, &leftMasked, &rightMasked, &error),
          "maps generate at 64 (mask on)");
    check(texel(leftMasked, 31, 31)[0] >= 0.0f, "mask keeps the center");
    check(texel(leftMasked, 0, 31)[0] == -1.0f && texel(leftMasked, 0, 31)[1] == -1.0f,
          "mask cuts the top edge (88.6° > 80°)");
    check(texel(leftMasked, 31, 0)[0] == -1.0f, "mask cuts the left edge");
    check(texel(leftMasked, 5, 5)[0] == -1.0f, "mask cuts the corner region");
    // Inside the porthole the mask must not perturb the mapping.
    check(texel(leftMasked, 31, 31)[0] == texel(left, 31, 31)[0] &&
          texel(leftMasked, 31, 31)[1] == texel(left, 31, 31)[1],
          "mask leaves interior texels untouched");

    // ---- fail-soft paths -------------------------------------------------
    ndi_brawmap::LensCalibration scratch;
    error.clear();
    check(!ndi_brawmap::parseCalibrationJSON(json.substr(0, json.size() / 2), &scratch, &error) &&
              !error.empty(),
          "truncated JSON fails soft");
    error.clear();
    check(!ndi_brawmap::parseCalibrationJSON("this is not json", &scratch, &error) && !error.empty(),
          "garbage fails soft");
    error.clear();
    check(!ndi_brawmap::parseCalibrationJSON("{\"captureDevice\":{\"views\":[]}}", &scratch, &error) &&
              !error.empty(),
          "missing views fails soft");
    {
        std::string wrongModel = json;
        const std::string needle = "radial2ProjectionOffsetTangential2";
        for (size_t at = wrongModel.find(needle); at != std::string::npos;
             at = wrongModel.find(needle, at)) {
            wrongModel.replace(at, needle.size(), "someFutureLensModel1234567890abcde");
        }
        error.clear();
        check(!ndi_brawmap::parseCalibrationJSON(wrongModel, &scratch, &error) &&
                  error.find("unsupported lens model") != std::string::npos,
              "unknown lens model fails soft with a clear error");
    }
    {
        std::string deep(ndi_brawmap::kMaxJsonDepth + 8, '[');
        error.clear();
        check(!ndi_brawmap::parseCalibrationJSON(deep, &scratch, &error) && !error.empty(),
              "hostile nesting fails soft");
    }
    {
        ndi_stmap::STMapImage bad;
        error.clear();
        check(!ndi_brawmap::generateEyeMap(cal.left, 4, false, &bad, &error) && !error.empty(),
              "undersized map request fails soft");
    }

    // ---- locale independence --------------------------------------------
    // strtod-based parsing breaks in comma-decimal locales; ours must not.
    if (std::setlocale(LC_NUMERIC, "de_DE.UTF-8") != nullptr ||
        std::setlocale(LC_NUMERIC, "de_DE") != nullptr) {
        ndi_brawmap::LensCalibration localeCal;
        error.clear();
        const bool ok = ndi_brawmap::parseCalibrationJSON(json, &localeCal, &error);
        check(ok, "parses under a comma-decimal locale");
        if (ok) {
            expectNear(localeCal.left.fx, 7765.9024452131525, 1e-6,
                       "numbers survive a comma-decimal locale");
        }
        std::setlocale(LC_NUMERIC, "C");
    } else {
        std::printf("ok   (locale test skipped — de_DE unavailable)\n");
    }

    if (failures) {
        std::fprintf(stderr, "%d FAILURE%s\n", failures, failures == 1 ? "" : "S");
    } else {
        std::printf("all brawmap tests passed\n");
    }
    return failures;
}
