#!/usr/bin/env python3
"""Golden-value generator for tests/test_brawmap.cpp.

Replicates the exact generateEyeMap() spec in double precision:
  row r (top-down), col c of a size x size map:
    lon = ((c+0.5)/size - 0.5)*pi     (+ right)
    lat = (0.5 - (r+0.5)/size)*pi     (+ up)
    d_rig = (cos(lat)sin(lon), -sin(lat), cos(lat)cos(lon))   x-right y-down z-fwd
    d_cam = R(quat) . d_rig
    invalid if d_cam.z < cos(calibLimit) or (d_cam.z + xi) <= 1e-9
    m = (x,y)/(z+xi); r2; L = 1+k1 r2+k2 r2^2
    xd = L mx + 2 p1 mx my + p2 (r2+2mx^2)
    yd = L my + p1 (r2+2my^2) + 2 p2 mx my
    u_px = fx xd + skew yd + cx;  v_px = fy yd + cy
    u_st = (u_px+0.5)/W;  v_st = 1-(v_px+0.5)/H
  mask ON additionally invalid if d_rig.z < cos(maskRadius)
"""
import json, math

cal = json.load(open("/Users/matthewcelia/Documents/repos/LSVR_ResolveOFX_NDIOutput/tests/fixtures/ursa_immersive_calibration.json"))
views = {v["viewDescription"]: v for v in cal["captureDevice"]["views"]}

def R_of(q):
    x, y, z, w = q
    n = math.sqrt(x*x+y*y+z*z+w*w)
    x, y, z, w = x/n, y/n, z/n, w/n
    return [
        [1-2*(y*y+z*z), 2*(x*y-z*w),   2*(x*z+y*w)],
        [2*(x*y+z*w),   1-2*(x*x+z*z), 2*(y*z-x*w)],
        [2*(x*z-y*w),   2*(y*z+x*w),   1-2*(x*x+y*y)],
    ]

def project(view, d):
    i = view["intrinsics"]
    k1, k2, xi, p1, p2 = i["distortions"]
    W, H = view["imageSize"]
    lim = math.radians(i["calibrationLimitRadialAngle"])
    x, y, z = d
    if z < math.cos(lim): return None
    denom = z + xi
    if denom <= 1e-9: return None
    mx, my = x/denom, y/denom
    r2 = mx*mx + my*my
    L = 1 + k1*r2 + k2*r2*r2
    xd = L*mx + 2*p1*mx*my + p2*(r2 + 2*mx*mx)
    yd = L*my + p1*(r2 + 2*my*my) + 2*p2*mx*my
    u = i["fx"]*xd + i["skew"]*yd + i["centerX"]
    v = i["fy"]*yd + i["centerY"]
    return ((u + 0.5)/W, 1.0 - (v + 0.5)/H, u, v)

def texel(view, size, r, c):
    lon = ((c + 0.5)/size - 0.5)*math.pi
    lat = (0.5 - (r + 0.5)/size)*math.pi
    d_rig = (math.cos(lat)*math.sin(lon), -math.sin(lat), math.cos(lat)*math.cos(lon))
    R = R_of(view["extrinsics"][0]["quat"])
    d_cam = tuple(sum(R[i][j]*d_rig[j] for j in range(3)) for i in range(3))
    return project(view, d_cam), d_rig

size = 64
print("// Golden values generated by docs/captures gen_goldens.py from")
print("// tests/fixtures/ursa_immersive_calibration.json (double precision).")
for eye in ("left", "right"):
    for (r, c) in [(31, 31), (10, 50), (55, 20), (0, 0), (63, 63), (31, 0)]:
        res, d_rig = texel(views[eye], size, r, c)
        if res is None:
            print(f"// {eye} r={r} c={c}: INVALID")
        else:
            u, v, upx, vpx = res
            print(f"{{ {0 if eye=='left' else 1}, {r}, {c}, {u:.9f}f, {v:.9f}f }},   // px=({upx:.2f},{vpx:.2f})")

# pure-projection golden: half the stated horizontal FOV, no rotation, left eye
th = math.radians(views["left"]["opticalData"]["Fov"]["horizontal"]/2)
res = project(views["left"], (math.sin(th), 0.0, math.cos(th)))
print(f"// hFov/2={math.degrees(th):.6f}deg -> u_px={res[2]:.4f} (sensor half-width 4080)")

# mask facts
pts = views["left"]["maskData"]["maskViewParameters"]["controlPoints"]
angs = [math.degrees(math.acos(max(-1.0, min(1.0, -p[2])))) for p in pts]
print(f"// mask: n={len(pts)} meanAngle={sum(angs)/len(angs):.6f} spread={max(angs)-min(angs):.6f}")

# which texels flip validity under the 80deg mask at size 64:
view = views["left"]
maskr = math.radians(sum(angs)/len(angs))
flips = []
for (r, c) in [(31, 31), (0, 31), (31, 0), (0, 0), (5, 5), (2, 31)]:
    _, d_rig = texel(view, size, r, c)
    inside = d_rig[2] >= math.cos(maskr)
    flips.append(((r, c), inside))
print("// mask-inside at size64:", flips)
